### ISSUE TITLE
Docker config

### ISSUE THREAD

**Issue by erik-valdivieso** [kukulkan-project/kukulkan-shell#4]
Change docker's configuration in maven plugin from:

```xml
<configuration>
    <repository>kukulkan</repository>
    <tag>latest</tag>
    <contextDirectory>${project.build.directory}</contextDirectory>
</configuration>
```

to:

```xml
<configuration>
    <repository>${project.artifactId}</repository>
    <contextDirectory>${project.build.directory}</contextDirectory>
    <imageTags>
       <imageTag>${project.version}</imageTag>
       <imageTag>latest</imageTag>
    </imageTags>
</configuration>
```

**Comment by robertovillarejo** [comment]
Solucionado en este [commit](https://github.com/kukulkan-project/kukulkan-generator-angularjs/commit/e31cd47094a10e96542ff8fdf7f3a4688ada3364) con solo el tag **latest**. Al parecer el plugin solo acepta un tag.

```
<configuration>
    <repository>${r"${project.artifactId}"}</repository>
    <tag>latest</tag>
    <contextDirectory>${r"${project.build.directory}"}</contextDirectory>
</configuration>
```

**Comment by robertovillarejo** [comment]
El plugin antiguo [Docker Maven Plugin](https://github.com/spotify/docker-maven-plugin) sí aceptaba múltiples tags: 
```
<build>
  <plugins>
    ...
    <plugin>
      <configuration>
        ...
        <imageTags>
           <imageTag>${project.version}</imageTag>
           <imageTag>latest</imageTag>
        </imageTags>
      </configuration>
    </plugin>
    ...
  </plugins>
</build>
```
El nuevo plugin [Dockerfile maven](https://github.com/spotify/dockerfile-maven) solo acepta un tag. 
Se discute la posibilidad de tener el `<tag>${project.version}</tag>` en lugar de `<tag>latest</tag>`. 
Sin embargo, habría que actualizar cada vez que se cambie a una nueva versión, el `app.yml` para que haya consistencia. 

```
version: '2'
services:
    demo-app:
        image: demo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://demo-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=demo
            - APP_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    demo-mongodb:
        extends:
            file: mongodb.yml
            service: demo-mongodb
 ```
Por lo pronto, se reabre el issue.
